ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_fk;
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_fk_1;
DROP TABLE IF EXISTS public.bookings;
CREATE TABLE IF NOT EXISTS public.bookings (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date timestamp without time zone NOT NULL, end_date timestamp without time zone NOT NULL, item_id int8 NOT NULL, booker_id int8 NOT NULL, status varchar NOT NULL, CONSTRAINT pk_booking PRIMARY KEY (id));
CREATE INDEX IF NOT EXISTS bookings_id_idx ON public.bookings (id);

DROP TABLE IF EXISTS public.requests;
CREATE TABLE IF NOT EXISTS public.requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description varchar NULL, requestor_id bigint NULL, CONSTRAINT pk_request PRIMARY KEY (id));

ALTER TABLE public."comments" DROP CONSTRAINT IF EXISTS comments_fk;
ALTER TABLE public."comments" DROP CONSTRAINT IF EXISTS comments_fk_1;
DROP TABLE IF EXISTS public."comments";
CREATE TABLE IF NOT EXISTS public."comments" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "text" varchar NOT NULL, item_id bigint NOT NULL, author_id bigint NOT NULL, created timestamp without time zone NOT NULL, CONSTRAINT pk_comment PRIMARY KEY (id));

ALTER TABLE public.items DROP CONSTRAINT IF EXISTS items_fk;
DROP TABLE IF EXISTS public.items;
CREATE TABLE IF NOT EXISTS public.items (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" varchar NOT NULL, description varchar NOT NULL, available bool NOT NULL, owner bigint NOT NULL, request bigint NOT NULL, CONSTRAINT pk_item PRIMARY KEY (id));
CREATE INDEX IF NOT EXISTS item_id_idx ON public.items (id);


DROP TABLE IF EXISTS public."users";
CREATE TABLE IF NOT EXISTS public."users" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" varchar NOT NULL, email varchar NOT NULL, CONSTRAINT pk_user PRIMARY KEY (id), CONSTRAINT UQ_USER_EMAIL UNIQUE (email));
CREATE INDEX IF NOT EXISTS user_id_idx ON public."users" USING btree (id);

ALTER TABLE public.bookings ADD CONSTRAINT bookings_fk FOREIGN KEY (booker_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_fk_1 FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE public."comments" ADD CONSTRAINT comments_fk FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE public."comments" ADD CONSTRAINT comments_fk_1 FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE public.items ADD CONSTRAINT items_fk FOREIGN KEY ("owner") REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE RESTRICT;